name: Release Workbench

on:
  push:
    branches:
      - 'osxPkg'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.container && matrix.container.image || matrix.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    needs: [release]
    container: ${{ matrix.container && matrix.container || null }}
    strategy:
      matrix:
        include:
          # X86
          - os: macos-13
            target: Macos
            flavour: mac
            name: Macos13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        if: ${{ matrix.flavour == 'mac' }}
        run: |
          export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV

          brew install python@3.11 gcc make
          brew install libev