name: Release Workbench

on:
  push:
    tags:
      - 'v*'
    branches:
      - develop

defaults:
  run:
    shell: bash

jobs:
  # release:
  #   name: Create Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Fail if tag is not prefixed by v
  #       run: |
  #         if [[ $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9].* ]]; then
  #             echo "Valid version format"
  #         else
  #             echo "Invalid version format"
  #             exit 1
  #         fi

  #     - name: Create release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         tag: ${{ github.ref_name }}
  #       run: |
  #         OPTIONS=""
  #         if [[ $GITHUB_REF_NAME == *"internal"* ]]; then
  #           OPTIONS="--prerelease"
  #         fi
  #         gh release create "$GITHUB_REF_NAME" \
  #             --repo="$GITHUB_REPOSITORY" \
  #             --title="Release for ${GITHUB_REF_NAME}" \
  #             --generate-notes $OPTIONS

  build:
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    #needs: [release]
    strategy:
      matrix:
        include:
          - os: [ubuntu-24.04]
            target: Linux
            name: ubuntu24
            flavour: ubuntu

          - os: [ubuntu-22.04]
            target: Linux
            name: ubuntu22
            flavour: ubuntu

          # - os: [ubuntu-22.04]
          #   target: Linux
          #   name: rocky9
          #   flavour: redhat
          #   container:
          #     image: rockylinux/rockylinux:9

          # X86
          # - os: macos-13
          #   target: Macos
          #   flavour: mac

          - os: windows-latest
            target: Windows
            flavour: windows
            runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get versions
        if: ${{ github.ref_name != 'develop' }}
        run: |
          echo "VERSION=$(echo $GITHUB_REF_NAME | sed 's/v//')" >> $GITHUB_ENV
          echo "VERSION=$VERSION"
          [ -f /etc/os-release ] && cat /etc/os-release

      - name: Setup Python v3.11
        uses: actions/setup-python@v5
        if: ${{ matrix.target != 'Windows' }}
        with:
          python-version: 3.11
          cache: "pip"

      - name: Compile and build (Ubuntu/Debian)
        if: ${{ matrix.flavour == 'ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libev-dev make libc6-dev ruby-rubygems
          python -m venv venv
          source venv/bin/activate
          pip install cython
          ./configure
          make -j4

      - name: Compile and build (Windows)
        if: ${{ matrix.target == 'Windows' }}
        run: |
          make -f Makefile.win build && \
          make -f Makefile.win package

      - name: Create package
        if: ${{ matrix.target == 'Linux' }}
        run: |
          sudo gem install --no-document fpm
          ./package.sh ${VERSION}

      - name: Upload Artifacts
        uses: softprops/action-gh-release@v2
        if: ${{ github.ref_name != 'develop' }}
        with:
          files: |
            *.zip
            *.rpm
            *.deb
            installer*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# code language: yaml
